[package]
name = "dirbkm"
version = "0.1.0"
authors = ["Poly <bartek.marynczak@op.pl>"]
edition = "2018"

[dependencies]
dialoguer = {path="./dialoguer"}

toml = "0.5.6"
serde = "1.0.104"
serde_derive = "1.0.104"